In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('gen ai.xlsx')

In [ ]:
df['Revenue Growth (%)'] = df.groupby('company')['total revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby('company')['net income'].pct_change() * 100

In [ ]:
df.head(9)

,years,company,total revenue,net income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%)
0,2023,microsoft,211.92,72.360,411.982,205.75,87.580,NaN,NaN
1,2022,microsoft,198.30,72.700,364.800,198.30,89.000,-6.426954,0.469873
2,2021,microsoft,168.10,61.300,333.800,191.80,76.700,-15.229450,-15.680880
3,2023,tesla,96.77,14.997,100.340,34.54,4.357,NaN,NaN
4,2022,tesla,81.46,12.556,82.340,30.33,7.561,-15.821019,-16.276589
5,2021,tesla,53.82,5.519,62.130,27.11,4.983,-33.930764,-56.044919
6,2023,apple,383.29,99.800,352.580,263.22,90.130,NaN,NaN
7,2022,apple,394.33,99.800,352.760,302.08,111.440,2.880326,0.000000
8,2021,apple,365.82,94.680,351.000,287.91,104.040,NaN,NaN

#Fill NA values that result from pct_change calculations with 0 or an appropriate value

In [ ]:
df.fillna(0, inplace=True)

In [ ]:
df.head(9)

,years,company,total revenue,net income,Total Assets,Total Liabilities,Cash Flow,Revenue Growth (%),Net Income Growth (%)
0,2023,microsoft,211.92,72.360,411.982,205.75,87.580,0.000000,0.000000
1,2022,microsoft,198.30,72.700,364.800,198.30,89.000,-6.426954,0.469873
2,2021,microsoft,168.10,61.300,333.800,191.80,76.700,-15.229450,-15.680880
3,2023,tesla,96.77,14.997,100.340,34.54,4.357,0.000000,0.000000
4,2022,tesla,81.46,12.556,82.340,30.33,7.561,-15.821019,-16.276589
5,2021,tesla,53.82,5.519,62.130,27.11,4.983,-33.930764,-56.044919
6,2023,apple,383.29,99.800,352.580,263.22,90.130,0.000000,0.000000
7,2022,apple,394.33,99.800,352.760,302.08,111.440,2.880326,0.000000
8,2021,apple,365.82,94.680,351.000,287.91,104.040,0.000000,0.000000

# summarizing these findings for each company

In [ ]:
summary = df.groupby('company').agg({
    'Revenue Growth (%)': 'mean',
    'Net Income Growth (%)': 'mean'
}).reset_index()

In [ ]:
print("\nYear-over-Year Average Growth Rates (%):")
print(summary)

Year-over-Year Average Growth Rates (%):
     company  Revenue Growth (%)  Net Income Growth (%)
0      apple            1.440163               0.000000
1     apple             0.000000               0.000000
2  microsoft           -7.218801              -5.070336
3      tesla          -16.583927             -24.107169